Support bailing on bash errors
- Exit when we have unexpected errors with `set -e`
- Avoid the default "" argument and just return usage since it didn't work as expected
- Fail when a pr branch name was not specified

diff --git a/src/git-code-review b/src/git-code-review
--- a/src/git-code-review
+++ b/src/git-code-review
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+# Sometimes we could have git errors and instead of barreling on,
+# we need to fail before error handling supports it.
+set -e
+
 USAGE="<COMMAND> [FLAGS] <pr_branch>
 
 Generate code-review branch that has been resolved against a base branch.
@@ -60,7 +64,6 @@ function start_code_review() {
     local pr_remote="$(git config code-review.pr-remote     || echo ${base_remote})"
     local branch_resolution_command="rebase"
 
-
     while [ $# -gt 0 ]; do
         case $1 in
             -b | --base)
@@ -93,6 +96,13 @@ function start_code_review() {
 
     # FIXME: The resolve method should be checked to make sure that it is either 'merge' or 'rebase'
 
+    # Need to make sure the user actually passed in a branch or else we'll fall apart
+    if [ -z ${pr_branch} ]; then
+        echo "No branch name was specified!"
+        usage
+        die
+    fi
+
     local merge_request_branch="code-review/${pr_branch}"
     require_work_tree_exists
     cd_to_toplevel
@@ -109,6 +119,7 @@ function start_code_review() {
         fetch "${pr_remote}"
     fi
 
+    echo "git branch '${merge_request_branch}' '${pr_branch}'"
     git branch "${merge_request_branch}" "${pr_branch}"
     git checkout "${merge_request_branch}"
     git branch --unset-upstream
@@ -124,7 +135,7 @@ function clean_up_current_branch() {
         echo "current branch was not created by git code-review"
         return 1
     fi
-    
+
     git checkout ${base_branch}
     git branch -D ${current_branch}
 }
@@ -134,9 +145,6 @@ function main() {
         "clear")
             shift 1
             clear_all "$@"
-            ;;
-        "")
-            start_code_review "$@"
             ;;
         "start")
             shift 1
